name: Deploy ortho_maker to S1-S5

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy runner and api to S1
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SHOST }}
          port: ${{ secrets.S1PORT }}
          username: ${{ secrets.SUSER }}
          key: ${{ secrets.S1KEY }}
          script: |
            cd /home/aerotract/software/ortho_maker
            git pull
            cd services/
            /home/aerotract/software/internal-tools/service-destroy.sh runner.service
            /home/aerotract/software/internal-tools/service-setup.sh runner.service
            /home/aerotract/software/internal-tools/service-destroy.sh api.service
            /home/aerotract/software/internal-tools/service-setup.sh api.service
      - name: deploy runner and api to S2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SHOST }}
          port: ${{ secrets.S2PORT }}
          username: ${{ secrets.SUSER }}
          key: ${{ secrets.S2KEY }}
          script: |
            cd /home/aerotract/software/ortho_maker
            git pull
            cd services/
            /home/aerotract/software/internal-tools/service-destroy.sh runner.service
            /home/aerotract/software/internal-tools/service-setup.sh runner.service
            /home/aerotract/software/internal-tools/service-destroy.sh api.service
            /home/aerotract/software/internal-tools/service-setup.sh api.service
      - name: deploy runner and api to S3
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SHOST }}
          port: ${{ secrets.S3PORT }}
          username: ${{ secrets.SUSER }}
          key: ${{ secrets.S3KEY }}
          script: |
            cd /home/aerotract/software/ortho_maker
            git pull
            cd services/
            /home/aerotract/software/internal-tools/service-destroy.sh runner.service
            /home/aerotract/software/internal-tools/service-setup.sh runner.service
            /home/aerotract/software/internal-tools/service-destroy.sh api.service
            /home/aerotract/software/internal-tools/service-setup.sh api.service
      - name: deploy runner and api to S4
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SHOST }}
          port: ${{ secrets.S4PORT }}
          username: ${{ secrets.SUSER }}
          key: ${{ secrets.S4KEY }}
          script: |
            cd /home/aerotract/software/ortho_maker
            git pull
            cd services/
            /home/aerotract/software/internal-tools/service-destroy.sh runner.service
            /home/aerotract/software/internal-tools/service-setup.sh runner.service
            /home/aerotract/software/internal-tools/service-destroy.sh api.service
            /home/aerotract/software/internal-tools/service-setup.sh api.service
      - name: deploy dashboard, runner, and api to S5
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SHOST }}
          port: ${{ secrets.S5PORT }}
          username: ${{ secrets.SUSER }}
          key: ${{ secrets.S5KEY }}
          script: |
            cd /home/aerotract/software/ortho_maker
            git pull
            cd services/
            /home/aerotract/software/internal-tools/service-destroy.sh dashboard.service
            /home/aerotract/software/internal-tools/service-setup.sh dashboard.service
            /home/aerotract/software/internal-tools/service-destroy.sh runner.service
            /home/aerotract/software/internal-tools/service-setup.sh runner.service
            /home/aerotract/software/internal-tools/service-destroy.sh api.service
            /home/aerotract/software/internal-tools/service-setup.sh api.service
